### PR TITLE
Fix paras pallet name

### PR DESCRIPTION
**Pull request by furoxr**
[#38](https://github.com/darwinia-network/darwinia-bridges-substrate/issues/38)

### CODE REVIEW

**Review by fewensa — APPROVED** [review]

**Review by wuminzhe — APPROVED** [review]

**Comment by AurevoirXavier** [comment]
Should this move to rococo primitives?

**Comment by fewensa** [comment]
I think to keep it there is better. this is used by pangolin 
https://github.com/darwinia-network/darwinia-common/blob/d9d29abece31b609085a48bf67bb7f15994d3e4c/node/runtime/pangolin/src/pallets/bridge_parachains.rs#L8

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-common/blob/main/node/runtime/pangolin/src/lib.rs#L244
https://github.com/darwinia-network/darwinia-bridges-substrate/blob/nada-fix-darwinia-v0.12.1/bin/millau/runtime/src/lib.rs#L535

**Comment by furoxr** [comment]
https://github.com/paritytech/parity-bridges-common/blob/6aece4f2327bb8c6e812b7913610f4fe93dc9bf9/bin/millau/runtime/src/lib.rs#L537-L548

https://github.com/paritytech/parity-bridges-common/blob/6aece4f2327bb8c6e812b7913610f4fe93dc9bf9/primitives/chain-rialto/src/lib.rs#L239

Parachain bridge related codes are at this branch "rialto-parachain-millau-messages-bridge"

**Pull request merged**
